-- Kim Industries - Material Orders: shared database setup.
-- Run once in Supabase: Dashboard > SQL Editor > New query > paste this file > Run.
-- Safe to re-run.

-- ---------------------------------------------------------------- orders
create table if not exists public.orders (
  id               text primary key,               -- generated by the app
  number           text unique,                    -- e.g. 24-118-001 (null until assigned)
  job_number       text not null,
  job_name         text,
  supplier         text not null,
  status           text not null default 'draft',  -- draft | sent
  requested_by     text,
  total            numeric(12,2),
  data             jsonb not null,                 -- full order incl. line items
  created_by       uuid default auth.uid() references auth.users(id) on delete set null,
  created_by_email text,
  created_at       timestamptz not null default now(),
  updated_at       timestamptz not null default now()
);
create index if not exists orders_job_number_idx on public.orders (upper(job_number));
create index if not exists orders_updated_at_idx on public.orders (updated_at desc);

-- ---------------------------------------------------------------- order numbers
-- One counter per job so every device gets the next number: <job>-001, -002, ...
create table if not exists public.job_counters (
  job_key  text primary key,
  last_seq integer not null default 0
);

create or replace function public.next_order_number(p_job text)
returns text
language plpgsql
security definer
set search_path = public
as $$
declare
  k text := upper(btrim(p_job));
  n integer;
begin
  if k is null or k = '' then
    raise exception 'job number is required';
  end if;
  insert into job_counters (job_key, last_seq) values (k, 1)
  on conflict (job_key) do update set last_seq = job_counters.last_seq + 1
  returning last_seq into n;
  return btrim(p_job) || '-' || lpad(n::text, 3, '0');
end;
$$;
revoke all on function public.next_order_number(text) from public, anon;
grant execute on function public.next_order_number(text) to authenticated;

-- ---------------------------------------------------------------- supplier contacts
create table if not exists public.supplier_contacts (
  supplier   text primary key,
  email      text,
  updated_at timestamptz not null default now()
);

-- ---------------------------------------------------------------- security
-- Only signed-in company users can read or write. The public (anon) key alone gets nothing.
alter table public.orders            enable row level security;
alter table public.job_counters      enable row level security;  -- no policies: only reachable through next_order_number()
alter table public.supplier_contacts enable row level security;

drop policy if exists "orders read"   on public.orders;
drop policy if exists "orders insert" on public.orders;
drop policy if exists "orders update" on public.orders;
drop policy if exists "orders delete" on public.orders;
create policy "orders read"   on public.orders for select to authenticated using (true);
create policy "orders insert" on public.orders for insert to authenticated with check (true);
create policy "orders update" on public.orders for update to authenticated using (true) with check (true);
-- Sent orders are kept for the record; only drafts can be deleted.
create policy "orders delete" on public.orders for delete to authenticated using (status = 'draft');

drop policy if exists "contacts read"   on public.supplier_contacts;
drop policy if exists "contacts write"  on public.supplier_contacts;
drop policy if exists "contacts update" on public.supplier_contacts;
create policy "contacts read"   on public.supplier_contacts for select to authenticated using (true);
create policy "contacts write"  on public.supplier_contacts for insert to authenticated with check (true);
create policy "contacts update" on public.supplier_contacts for update to authenticated using (true) with check (true);
