#!/usr/bin/env python3
"""Convert the Material Dashboard price list (.xlsx) into data/catalog.js for the app.

Usage:
    pip install openpyxl
    python3 scripts/build_catalog.py [path/to/Material_Dashboard.xlsx]

Expected columns (first sheet, header row 1):
    Item Name | Unit | Categories | Expected Price | Manufacturer | Model Number | Internal Identifier | UPC
"Manufacturer" is treated as the supplier the item is ordered from.

data/source/model_overrides.csv (supplier,id,model,note) replaces the model number of listed items,
e.g. to use a supplier's own part numbers from a quote. Prices are never changed by it.
"""
import csv
import json
import os
import sys
from datetime import date

import openpyxl

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
SRC = sys.argv[1] if len(sys.argv) > 1 else os.path.join(ROOT, "data", "source", "Material_Dashboard.xlsx")
OUT = os.path.join(ROOT, "data", "catalog.js")
OVERRIDES = os.path.join(ROOT, "data", "source", "model_overrides.csv")

UNIT_ALIASES = {"GALLON": "GAL", "QUART": "QT", "BOX": "BX", "SHT": "SH"}


def clean(v):
    return " ".join(str(v).split()) if v is not None else ""


def main():
    wb = openpyxl.load_workbook(SRC, read_only=True, data_only=True)
    ws = wb.worksheets[0]
    rows = ws.iter_rows(values_only=True)
    header = [clean(h).lower() for h in next(rows)]

    def col(name):
        return header.index(name.lower())

    c_name, c_unit, c_cat, c_price = col("Item Name"), col("Unit"), col("Categories"), col("Expected Price")
    c_sup, c_model, c_id = col("Manufacturer"), col("Model Number"), col("Internal Identifier")

    suppliers, categories, units, items = [], [], [], []
    idx = {"s": {}, "c": {}, "u": {}}

    def intern(kind, lst, value):
        if value not in idx[kind]:
            idx[kind][value] = len(lst)
            lst.append(value)
        return idx[kind][value]

    overrides = {}
    if os.path.exists(OVERRIDES):
        with open(OVERRIDES, newline="", encoding="utf-8") as f:
            for o in csv.DictReader(f):
                overrides[(o["supplier"].strip(), o["id"].strip())] = o["model"].strip()
    used = set()

    seen = set()
    for r in rows:
        name = clean(r[c_name])
        if not name:
            continue
        sup = clean(r[c_sup]) or "Unassigned"
        unit = clean(r[c_unit]).upper() or "EA"
        unit = UNIT_ALIASES.get(unit, unit)
        cat = " > ".join(p.strip() for p in clean(r[c_cat]).split(">") if p.strip()) or "Uncategorized"
        try:
            price = round(float(r[c_price] or 0), 4)
        except (TypeError, ValueError):
            price = 0
        model = clean(r[c_model])
        iid = clean(r[c_id]) or f"{sup}:{model or name}"
        if (sup, iid) in overrides:
            model = overrides[(sup, iid)]
            used.add((sup, iid))
        key = f"{sup}|{iid}"
        if key in seen:  # keep ids unique within a supplier
            iid = f"{iid}-{len(items)}"
        seen.add(f"{sup}|{iid}")
        items.append([
            name,
            intern("u", units, unit),
            intern("c", categories, cat),
            price,
            model,
            iid,
            intern("s", suppliers, sup),
        ])

    payload = {
        "source": os.path.basename(SRC),
        "built": date.today().isoformat(),
        "suppliers": suppliers,
        "categories": categories,
        "units": units,
        "fields": ["name", "unit", "category", "price", "model", "id", "supplier"],
        "items": items,
    }
    with open(OUT, "w", encoding="utf-8") as f:
        f.write("/* Generated by scripts/build_catalog.py - do not edit by hand. */\n")
        f.write("window.CATALOG = ")
        json.dump(payload, f, ensure_ascii=False, separators=(",", ":"))
        f.write(";\n")
    for k in overrides.keys() - used:
        print(f"WARNING: model override for {k[0]} item {k[1]} matched nothing")
    print(f"Applied {len(used)} model overrides")
    print(f"Wrote {len(items)} items, {len(suppliers)} suppliers, {len(categories)} categories -> {OUT}")


if __name__ == "__main__":
    main()
